### ISSUE TITLE
delete - idea for implementation

### ISSUE THREAD

**Issue by RobTillaart** [arkhipenko/Dictionary#1]
Thanks for this useful library.

Some ideas to implement the deletion of an element in a pretty memory efficient way.
1. Add a **bool deleted;** to every node.  This will increase the RAM memory usage. A more efficient way might be a shadow bit-array that can hold 8 bools per byte. 

2. Set the most significant bit of the first char of the key.
```
keystr[0] ^= 0x80;
```
The key field typically contains ASCII so highest bit is not set normally.
This would not add memory and would allow for undelete as well.

For all methods the deleted nodes stay in memory (no difficult re balancing) and they could in theory be reused,

To be able to iterate over the dictionary, implement functions like these that skip deleted keys.
- dict.first();  // returns 1st node or NULL
- dict.next();
- dict.prev();
- dict.last();
The latter two are optional. 

Just to share.

**Comment by arkhipenko** [comment]
As they say - let's talk about it. 
What would be a material use case where having an empty value returned for "deleted" vs never added key not work. I am only starting to use this library myself :) (in conjunction with EspBootstrap) and using it only for storing configuration parameters for my esp projects, so I did not think about other cases...

**Comment by RobTillaart** [comment]
The added value of the delete option is that it is not visible anymore.

If you walk through the dictionary. That would result e.g. in a smaller and therefor faster parse-able JSON file. The reason could be dependency between fields.
E.g. you want to describe a communication channel and the first field is TYPE and values are TCP UDP and Serial. Than one could expect that if TCP was chosen, that there would be no baudrate anymore or so.

Another application could be if I use a dict for holding keyValue pairs and at some moment a certain key is out of scope it doesn't need to be (visible) in the dict anymore. E.g. a game whack the mole could have different moles in the dict until they are whacked.

just some thoughts

**Comment by arkhipenko** [comment]
> The added value of the delete option is that it is not visible anymore.

That part I understand :)  There is a difference between "not there" and "empty" value - I get that. 

I think if I add a pointer to the parent, I can actually detach a b-tree node quite quickly (at the expense of 4 bytes per node of memory). The issue is an internal array I use for quickly and efficiently iterating through the nodes. 

Perhaps I can add a compile option `#define _DELETE_KEYS_` and switch back to in-order b-tree parsing, which requires an iterator object instead of simple direct index access. 

I am balancing simplicity, efficiency and memory footprint vs. functionality.
In both of your use cases, I believe there is a way to solve them with a bit of code or creating key/value checking.
  
Do you see the dilemma? Add code and memory for everyone, or let individual developers deal with corner cases?

**Comment by RobTillaart** [comment]
I would choose ==> let individual developers deal with corner cases?
Keeping it simple is preferred for 99% of the apps I've been involved in.

An other option came in my mind, when a node is deleted one could rebuild the tree?
Not very efficient, a bit like heapsort.

**Comment by arkhipenko** [comment]
> Another option came in my mind, when a node is deleted one could rebuild the tree?
> Not very efficient, a bit like heapsort.

I think that with a compile option is the way - if you absolutely need it - you can pay the performance price for it. 

Let me think about it... I was wondering what I am going to do with this next. Nothing more rewarding and depressing at the same time as finishing an interesting project, right?

**Comment by arkhipenko** [comment]
https://www.geeksforgeeks.org/binary-search-tree-set-2-delete/

**Comment by arkhipenko** [comment]
I think I am homing on a solution - BST deletion per the article and a rebuild of the index array via in-order traversal (or move the array elements actually - still faster than total array rebuild).

**Comment by RobTillaart** [comment]
the proof is in the performance test ...

**Comment by arkhipenko** [comment]
Done.

**Comment by RobTillaart** [comment]
Thanks for adding the remove.

Did you test the remove loop mentioned in the readme.md?
```
for (int i=0; i < d.count(); i++) {
  d.remove(d(0));
}
```
If the d.count() is evaluated every iteration it will not work correctly as i got bigger and d.count() got smaller. They will "meet" twice as fast. If the loop would start wit i = d.count() it is more robust

A robust remove loop that evaluates d.count() in every iteration is
```
while (d.count() > 0) d.remove(d(0));
```

**Comment by arkhipenko** [comment]
Goof catch! Thank you. Fixed.
