### ISSUE TITLE
dictionnaire in a separate .h file

### ISSUE THREAD

**Issue by Glujaz** [arkhipenko/Dictionary#15]
Hi there,

I'm trying to do a code using Homespan library, and was interested by your library as it lets me store in one easy to find location all the elements I need (in my case, for a TV connected over RS232, I would have one dictionary for each input, in which I find the name, the index, the activation command, a confirmation command).

When working in one giant ino file, it works. However, I'd like to have the dictionary on a separated tab, and just it. How could I do this ? I understand it needs a function, but I can't make a dictionary permanent so it works everywhere in my full code right ?

Sorry for this stupid question, I very very new to this (inducing C++)... Though, already quite proud of what I already achieved ! 😄

**Comment by arkhipenko** [comment]
Hi @Glujaz 
There are two files:
[Dictionary.h](https://github.com/arkhipenko/Dictionary/blob/master/src/Dictionary.h) and
[DictionaryDeclarations.h](https://github.com/arkhipenko/Dictionary/blob/master/src/DictionaryDeclarations.h)

Please follow the guidance on how to deal with multi-tab situation in the examples of the other library here:
https://github.com/arkhipenko/TaskScheduler/tree/master/examples/Scheduler_example16_Multitab
Same exact approach.
