### ISSUE TITLE
Separate into .h file and .cpp file

### ISSUE THREAD

**Issue by gadget1999** [arkhipenko/Dictionary#4]
It seems the current implementation is in the .h file. This is causing issue when I need to include the Dictionary.h file in a class header, which results in the implementation get compiled multiple times in the project and linker complains about the duplicate implementations found in multiple cpp files that include the header file.

Is it possible to separate out the implementation into .cpp file?

**Comment by arkhipenko** [comment]
It's an Arduino IDE legacy issue - if I do that I cannot use #define statements to control the library compilation parameters. 
I might need to do what I did for TaskScheduler - separate into 
Dictonary.h and DictionaryDeclarations.h 
Whenever I have time...

**Comment by arkhipenko** [comment]
There are two files:
[Dictionary.h](https://github.com/arkhipenko/Dictionary/blob/master/src/Dictionary.h) and
[DictionaryDeclarations.h](https://github.com/arkhipenko/Dictionary/blob/master/src/DictionaryDeclarations.h)

Please follow the guidance on how to deal with multi-tab situations in the examples of the other library here:
https://github.com/arkhipenko/TaskScheduler/tree/master/examples/Scheduler_example16_Multitab
Same exact approach.
