### ISSUE TITLE
Is there any plan to be directly compatible with NodeMCU?

### ISSUE THREAD

**Issue by LianYangCn** [arkhipenko/Dictionary#7]
Is there any plan to be directly compatible with NodeMCU?

, and integrate with [ESP32Himem](https://github.com/arkhipenko/ESP32Himem)

^_^

**Comment by arkhipenko** [comment]
If you mean esp8266-based node MCU - it is already. It's just Node MCU doesn't have much memory, so you won't store more than 300-400 keys.

**Comment by arkhipenko** [comment]
Esp8266 does not have PSRAM, so no Himem

**Comment by arkhipenko** [comment]
If you mean NodeMCU ESP32 - you can use Dictionary as is, but no Himem - there is no PSRAM on that board.
