### ISSUE TITLE
Memory Leak and ESP32 destroy() Error

### ISSUE THREAD

**Issue by frezik** [arkhipenko/Dictionary#9]
My application downloads a JSON string once an hour, which is used as a local cache.  The data is around 400 entries of 10-digit numeric strings as keys, and booleans as values. There seems to be a memory leak that builds up over time, which eventually prevents the JSON from being parsed.  This is on an ESP32. I do not have PSRAM on this particular board.

Following the documented advice to recreate the object rather than calling `destroy()`, I initially did this by simply assigning the new cache to the old:

    Dictionary *new_cache = new Dictionary( 8192 );
    new_cache->jload( JSON );
    cache = new_cache;

After a few iterations to have memory usage settle, this seems to leak 80 bytes per iteration.  I also tried to add a `cache->destroy()` before assigning the new cache, but this caused a fatal error on the ESP32:

===============
[START]
Heap available at start: 369460
1 attempt
    Heap before rebuild: 369460
    Heap after allocation: 369380
    Heap after JSON parse: 299812
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d0fb7  PS      : 0x00060530  A0      : 0x800d1508  A1      : 0x3ffb1f60  
A2      : 0x00000000  A3      : 0x3ffbfec0  A4      : 0x00000000  A5      : 0x00000003  
A6      : 0x00000003  A7      : 0x00000000  A8      : 0x800d1b14  A9      : 0x3ffb1f40  
A10     : 0x3ffb1f80  A11     : 0x00000006  A12     : 0x0000000a  A13     : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

ELF file SHA256: 0000000000000000

Backtrace: 0x400d0fb7:0x3ffb1f60 0x400d1505:0x3ffb1f80 0x400d28b9:0x3ffb1fb0 0x400860ed:0x3ffb1fd0

Rebooting...

===============

Here's the output without calling `destroy()`:

[output.txt](https://github.com/arkhipenko/Dictionary/files/7604992/output.txt)

And the test program with data similar to what's being loaded in my full program:

[dictionary_memleak.txt](https://github.com/arkhipenko/Dictionary/files/7604993/dictionary_memleak.txt)

**Comment by arkhipenko** [comment]
Please send source code. I suspect you don't destroy the actual dictionary object.
Where is `delete new_cache`?

**Comment by frezik** [comment]
Source code is in dictionary_memleak.txt (github doesn't let you attach .ino files).

`new_cache` simply becomes `cache` after being loaded on each iteration through the rebuild.

**Comment by arkhipenko** [comment]
1. As I suspected you never destroy the actual Dictionary object - you created a memory leak by creating a new Dictionary and never deleting the old one. This is a classic "dropping pointers" scenario. C++ is not a managed language, you have to manage your objects. 
2. 8192 objects maybe too much for esp32 heap without PSRAM - start with a few hundred and experiment. 
```
void loop()
{
    times_rebuilt++;

    Serial.print( times_rebuilt );
    Serial.println( " attempt" );
    log_mem( "    Heap before rebuild: " );
   new_cache = NULL;
    Dictionary *new_cache = new Dictionary( dict_size );
// where is error handling?
   if ( new_cache  ) {
    log_mem( "    Heap after allocation: " );
    
    new_cache->jload( JSON );
    log_mem( "    Heap after JSON parse: " );

    // Fatal error on ESP32
    //cache->destroy();

    //cache = new_cache;  this does nothing in C++
   delete new_cache;
   }
   else {
     // there was a memory allocation error
   }
    log_mem( "    Heap after replacing cache: " );
}
```

By the way, the dictionary was never meant to operate with boolean values. It clearly states that the only supported type is String.

**Comment by arkhipenko** [comment]
Also, did you check the return value of `new_cache->jload( JSON );`? It must have returned an error.

**Comment by arkhipenko** [comment]
`cache->destroy();`
cache is undefined (NULL) on the first iteration, that caused the panic
